# Generated by Django 4.2.2 on 2023-08-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('project_pic', models.ImageField(upload_to='images/')),
                ('project_live_link', models.CharField(blank=True, max_length=300, null=True)),
                ('project_source_link', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
