# Generated by Django 4.2.2 on 2023-08-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='word_count',
        ),
    ]
